import React, { Component } from 'react'

import { BACKEND, TEAM_IMAGE } from '../../config'

import './games.css'



/**
 * The games page which shows the detail of the game, which contains the winner,
 * each players' stat in that game, and possibly the mvp of the game ( generated by users' votes )
 */
class Games extends Component {

    constructor(props) {
        super(props);
        this.state = {
            stats : [],
            id : this.props.match.params.gameId,
            map : {},
            gameInfo : {}
        };
        this.getStats = this.getStats.bind( this );
        this.getTeamMap = this.getTeamMap.bind(this);
        this.getGameInfo = this.getGameInfo.bind(this);
    }

    componentDidMount() {
        this.getStats();
        this.getGameInfo();
        this.getTeamMap();
    }

    getStats = function() {
        let url = BACKEND + '/games/gameStats/' + this.state.id;
        fetch( url ).then( res => {
            return res.json();
        }).then( data => {
            this.setState( { stats : data } );
        });
    };

    getGameInfo = function() {
        let url = BACKEND + '/games/gameInfo/' + this.state.id;
        fetch( url ).then( res => {
            return res.json();
        }).then( data => {
            this.setState( { gameInfo : data } );
        });
    };

    /**
     * get a map which maps the id of a team to the name of the team
     */
    getTeamMap = function() {
        let url = BACKEND + '/teamMap';
        fetch( url ).then( res => {
            return res.json();
        }).then( data => {
            this.setState( { map : data } )
        });
    };

    render() {
        return (
            <div className='gamesOuterBox'>
                <div className='gamesInnerBox'>
                    <img src={ TEAM_IMAGE + this.state.map[this.state.gameInfo.team1_id] + '_logo.svg' } className='infoImg'/>
                    <img src={ TEAM_IMAGE + this.state.map[this.state.gameInfo.team2_id] + '_logo.svg' } className='infoImg'/>
                </div>
                <table className='gamesTable'>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>PTS</th>
                                <th>REB</th>
                                <th>AST</th>
                                <th>STL</th>
                                <th>BLK</th>
                                <th>TOV</th>
                                <th>3PA</th>
                                <th>3PM</th>
                                <th>FGA</th>
                                <th>FGM</th>
                                <th>MIN</th>
                            </tr>
                        </thead>
                        <tbody>
                            { this.state.stats.map( ( element, idx) => {
                                let row = 'odd';
                                if ( idx % 2 === 0) {
                                    row = 'even';
                                }
                                return (
                                    <tr className={ row }>
                                        <th>{ element.name }</th>
                                        <th>{ element.scores }</th>
                                        <th>{ element.rebounds }</th>
                                        <th>{ element.assists }</th>
                                        <th>{ element.steals }</th>
                                        <th>{ element.blocks }</th>
                                        <th>{ element.turnovers }</th>
                                        <th>{ element.three_hit }</th>
                                        <th>{ element.three_made }</th>
                                        <th>{ element.hit }</th>
                                        <th>{ element.made }</th>
                                        <th>{ element.time }</th>
                                    </tr>
                                )
                            } ) }
                        </tbody>
                    </table>
            </div>
        )
    }
}

export default Games;