import React, { Component } from 'react'

import { BACKEND } from '../../config'
import {Link} from "react-router-dom";


/**
 * The games page which shows the detail of the game, which contains the winner,
 * each players' stat in that game, and possibly the mvp of the game ( generated by users' votes )
 */
class Games extends Component {

    constructor(props) {
        super(props);
        this.state = {
            stats : [],
            id : this.props.match.params.gameId
        };
        this.getStats = this.getStats.bind( this );
    }

    componentDidMount() {
        this.getStats();
    }

    getStats = function() {
        let url = BACKEND + '/games/' + this.state.id;
        fetch( url ).then( res => {
            return res.json();
        }).then( data => {
            this.setState( { stats : data } );
        });
    };

    render() {
        return (
            <div>
                <table>
                        <thead>
                            <tr>
                                <th>Name</th>
                                <th>PTS</th>
                                <th>REB</th>
                                <th>AST</th>
                                <th>STL</th>
                                <th>BLK</th>
                                <th>TOV</th>
                                <th>3PA</th>
                                <th>3PM</th>
                                <th>FGA</th>
                                <th>FGM</th>
                                <th>MIN</th>
                            </tr>
                        </thead>
                        <tbody>
                            { this.state.stats.map( ( element, idx) => {
                                let row = 'odd';
                                if ( idx % 2 === 0) {
                                    row = 'even';
                                }
                                return (
                                    <tr className={ row }>
                                        <th>{ element.name }</th>
                                        <th>{ element.scores }</th>
                                        <th>{ element.rebounds }</th>
                                        <th>{ element.assists }</th>
                                        <th>{ element.steals }</th>
                                        <th>{ element.blocks }</th>
                                        <th>{ element.turnovers }</th>
                                        <th>{ element.three_hit }</th>
                                        <th>{ element.three_made }</th>
                                        <th>{ element.hit }</th>
                                        <th>{ element.made }</th>
                                        <th>{ element.time }</th>
                                    </tr>
                                )
                            } ) }
                        </tbody>
                    </table>
            </div>
        )
    }
}

export default Games;